% createfigurek(k_comp,'Sensitivity','Parameter $k$',[0:10:100],[0:0.5:1],3,1,'NorthEast','')
function figure1=createfigure(YMatrix1,x_label,y_label,vct_x,vct_y,pt,xscale,legend_pos,save_name)
%CREATEFIGURE1(YMATRIX1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 19-Mar-2013 17:33:45

% Create figure
figure1 = figure('Color',[1 1 1]);
font_size=20;
colormap('lines');


tick_value_x=unique(sort([vct_x ]));%pt*xscale]));
tmp=num2cell(tick_value_x/xscale);
for r=1:1:numel(tmp)
x_tick_label{1,r}=num2str(tmp{1,r});
end

tick_value_y=vct_y;

% Create axes
axes1 = axes('Parent',figure1,'YTick',tick_value_y,'YMinorTick','off','YGrid','on',...
    'XTick',tick_value_x,'XTickLabel',x_tick_label,...
    'XMinorTick','off',...
    'XGrid','on',...
    'FontName','Times New Roman','FontSize',font_size);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 100]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 1]);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'Parent',axes1);
set(plot1(1),'LineWidth',2,'Color',[1 0 0],'DisplayName','Test Case 1');
set(plot1(2),'LineWidth',2,'Color',[0 1 0],'DisplayName','Test Case 2');
set(plot1(3),'LineWidth',2,'Color',[1 0 1],'DisplayName','Test Case 3');
set(plot1(4),'LineWidth',2,'Color',[0 0 1],'DisplayName','Test Case 4');
set(plot1(5),'LineWidth',2,'Color',[0 1 1],'DisplayName','Test Case 5');

% Create stem
stem(pt*xscale,YMatrix1(uint8(pt*xscale),1),'LineWidth',2,...
    'Color',[0.400000005960464 0.200000002980232 0],...
    'Parent',axes1,...
    'DisplayName',['Optimum Value = ' num2str(pt)]);


% Create xlabel
xlabel(['\textbf{' x_label ' $\longrightarrow$}'],'Interpreter','latex',...
    'FontSize',font_size);

% Create ylabel
ylabel(['\textbf{' y_label '$\longrightarrow$}'],'Interpreter','latex',...
    'FontSize',font_size);

% Create light
light('Parent',axes1,...
    'Position',[-0.99938390316437 0.00576994565515728 0.0346196739309437]);


% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location',legend_pos,'FontSize',font_size);

if ~isequal(save_name,'')
    saveas(figure1,['.\htmlC\' save_name '.png']);
    saveas(figure1,['.\htmlC\' save_name '.eps'],'psc2');
    saveas(figure1,['.\htmlC\' save_name '.fig']);
    snapnow
    close(figure1)
end

