function [handle]=createmeshfigure(ph)
%CREATEFIGURE(XDATA1,YDATA1,ZDATA1)
%  XDATA1:  surface xdata
%  YDATA1:  surface ydata
%  ZDATA1:  surface zdata

%  Auto-generated by MATLAB on 28-Aug-2012 21:35:40

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1,'FontName','Times New Roman');
view(axes1,[-37.5 30]);
grid(axes1,'on');
hold(axes1,'all');

% Create mesh
handle=mesh(ph,'Parent',axes1);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% Create zlabel
zlabel('radius','FontWeight','bold','FontSize',12,...
    'FontName','Times New Roman');

% Create xlabel
xlabel('column','FontWeight','bold','FontSize',12,...
    'FontName','Times New Roman');

% Create ylabel
ylabel('row','FontWeight','bold','FontSize',12,'FontName','Times New Roman');

            zlabel('radius');xlabel('column');ylabel('row');
